In [ ]:
with open("API_KEY.txt") as file:
    API_KEY = file.read()

print(API_KEY)

In [ ]:
%pip install --upgrade pip

In [ ]:
from alpha_vantage.timeseries import TimeSeries
import requests
from bs4 import BeautifulSoup
import pandas as pd
import io

In [ ]:
ts1 = TimeSeries(API_KEY)

In [ ]:
# AAPL is Apple Stock Market
ts1.get_monthly("AAPL")

In [ ]:
ts1.get_weekly("AAPL")

In [ ]:
ts1.get_intraday("AAPL")

Exploring Alpha Vantage API using requests Package

In [ ]:
# Getting stock values monthly

url = 'https://www.alphavantage.co/query?function=TIME_SERIES_MONTHLY&symbol=AAPL&apikey=' + str(API_KEY)
r = requests.get(url)
data = r.json()

print(data)

In [ ]:
# getting stock values weekly

url = 'https://www.alphavantage.co/query?function=TIME_SERIES_WEEKLY&symbol=AAPL&apikey=' + str(API_KEY)
r = requests.get(url)
data = BeautifulSoup(r.content)

print(data)

How to put a stock data into a DataFrame

Requests Methods

In [ ]:
url = 'https://www.alphavantage.co/query?function=TIME_SERIES_WEEKLY&symbol=AAPL&apikey=' + str(API_KEY) + '&datatype=csv'
r = requests.get(url).content
data = pd.read_csv(io.StringIO(r.decode('utf-8')))

print(data)

In [ ]:
data.head(10)

In [ ]:
apple1, meta_data = ts1.get_intraday("AAPL", outputsize="full")

print(meta_data)
print(apple1)

In [ ]:
meta_data

In [ ]:
apple1

In [ ]:
# store data into a dataframe

df_apple1 =  pd.DataFrame(apple1).transpose().reset_index()
df_apple1.head()

In [27]:
ts1.get_intraday("AAPL")

({'2024-01-19 19:45:00': {'1. open': '191.2300',
   '2. high': '191.3100',
   '3. low': '191.1600',
   '4. close': '191.2300',
   '5. volume': '7448'},
  '2024-01-19 19:30:00': {'1. open': '191.2200',
   '2. high': '191.2500',
   '3. low': '191.0600',
   '4. close': '191.2200',
   '5. volume': '6076'},
  '2024-01-19 19:15:00': {'1. open': '191.1100',
   '2. high': '191.3800',
   '3. low': '191.1100',
   '4. close': '191.2200',
   '5. volume': '3551'},
  '2024-01-19 19:00:00': {'1. open': '191.3000',
   '2. high': '191.3000',
   '3. low': '191.0900',
   '4. close': '191.2400',
   '5. volume': '11999'},
  '2024-01-19 18:45:00': {'1. open': '191.4300',
   '2. high': '191.4300',
   '3. low': '191.2700',
   '4. close': '191.3000',
   '5. volume': '8553'},
  '2024-01-19 18:30:00': {'1. open': '191.4500',
   '2. high': '191.5200',
   '3. low': '191.4050',
   '4. close': '191.4200',
   '5. volume': '4244'},
  '2024-01-19 18:15:00': {'1. open': '191.4900',
   '2. high': '191.5600',
   '3. low': '191.3800',
   '4. close': '191.5000',
   '5. volume': '119949'},
  '2024-01-19 18:00:00': {'1. open': '191.4350',
   '2. high': '191.5500',
   '3. low': '191.3900',
   '4. close': '191.5100',
   '5. volume': '2385'},
  '2024-01-19 17:45:00': {'1. open': '191.4400',
   '2. high': '191.4900',
   '3. low': '191.3800',
   '4. close': '191.4350',
   '5. volume': '3421'},
  '2024-01-19 17:30:00': {'1. open': '191.4600',
   '2. high': '191.5000',
   '3. low': '181.6570',
   '4. close': '191.4200',
   '5. volume': '5945'},
  '2024-01-19 17:15:00': {'1. open': '191.5200',
   '2. high': '200.0630',
   '3. low': '191.4500',
   '4. close': '191.4750',
   '5. volume': '3937'},
  '2024-01-19 17:00:00': {'1. open': '191.5550',
   '2. high': '191.5900',
   '3. low': '191.5000',
   '4. close': '191.5300',
   '5. volume': '5670'},
  '2024-01-19 16:45:00': {'1. open': '191.4600',
   '2. high': '191.7600',
   '3. low': '191.4600',
   '4. close': '191.5550',
   '5. volume': '23477'},
  '2024-01-19 16:30:00': {'1. open': '191.3900',
   '2. high': '191.5600',
   '3. low': '191.3500',
   '4. close': '191.4650',
   '5. volume': '225141'},
  '2024-01-19 16:15:00': {'1. open': '191.4900',
   '2. high': '198.8700',
   '3. low': '190.7540',
   '4. close': '191.3800',
   '5. volume': '52358'},
  '2024-01-19 16:00:00': {'1. open': '191.5600',
   '2. high': '191.6000',
   '3. low': '190.8930',
   '4. close': '191.4900',
   '5. volume': '21590783'},
  '2024-01-19 15:45:00': {'1. open': '191.4100',
   '2. high': '191.8200',
   '3. low': '191.3200',
   '4. close': '191.5800',
   '5. volume': '3995109'},
  '2024-01-19 15:30:00': {'1. open': '191.4340',
   '2. high': '191.6500',
   '3. low': '191.3900',
   '4. close': '191.4110',
   '5. volume': '1721562'},
  '2024-01-19 15:15:00': {'1. open': '191.5700',
   '2. high': '191.6400',
   '3. low': '191.3200',
   '4. close': '191.4350',
   '5. volume': '1395544'},
  '2024-01-19 15:00:00': {'1. open': '191.6540',
   '2. high': '191.7400',
   '3. low': '191.4800',
   '4. close': '191.5700',
   '5. volume': '1621255'},
  '2024-01-19 14:45:00': {'1. open': '191.3700',
   '2. high': '191.6700',
   '3. low': '191.1950',
   '4. close': '191.6500',
   '5. volume': '1749157'},
  '2024-01-19 14:30:00': {'1. open': '191.4800',
   '2. high': '191.6400',
   '3. low': '191.1700',
   '4. close': '191.3800',
   '5. volume': '1657227'},
  '2024-01-19 14:15:00': {'1. open': '191.9300',
   '2. high': '191.9500',
   '3. low': '191.3700',
   '4. close': '191.4700',
   '5. volume': '1962473'},
  '2024-01-19 14:00:00': {'1. open': '191.4100',
   '2. high': '191.9500',
   '3. low': '191.4100',
   '4. close': '191.9350',
   '5. volume': '1892428'},
  '2024-01-19 13:45:00': {'1. open': '191.4200',
   '2. high': '191.4500',
   '3. low': '191.1600',
   '4. close': '191.4140',
   '5. volume': '1388047'},
  '2024-01-19 13:30:00': {'1. open': '190.9340',
   '2. high': '191.4350',
   '3. low': '190.9250',
   '4. close': '191.4200',
   '5. volume': '1607285'},
  '2024-01-19 13:15:00': {'1. open': '190.7000',
   '2. high': '190.9900',
   '3. low': '190.6900',
   '4. close': '190.9350',
   '5. volume': '2114711'},
  '2024-01-19 13:00:00': {'1. open': '190.5650',
   '2. high': '190.7650',
   '3. low': '190.4950',
   '4. close': '190.7000',
   '5. volume': '2580871'},
  '2024-01-19 12:45:00': {'1. open': '190.4350',
   '2. high': '190.5900',
   '3. low': '190.2800',
   '4. close': '190.5650',
   '5. volume': '927358'},
  '2024-01-19 12:30:00': {'1. open': '190.3200',
   '2. high': '190.6400',
   '3. low': '190.2920',
   '4. close': '190.4300',
   '5. volume': '1561952'},
  '2024-01-19 12:15:00': {'1. open': '190.0900',
   '2. high': '190.4300',
   '3. low': '189.9100',
   '4. close': '190.3150',
   '5. volume': '1635884'},
  '2024-01-19 12:00:00': {'1. open': '189.9750',
   '2. high': '190.1400',
   '3. low': '189.9000',
   '4. close': '190.0900',
   '5. volume': '1640275'},
  '2024-01-19 11:45:00': {'1. open': '189.5700',
   '2. high': '190.0300',
   '3. low': '189.3300',
   '4. close': '189.9750',
   '5. volume': '1344035'},
  '2024-01-19 11:30:00': {'1. open': '189.9000',
   '2. high': '189.9800',
   '3. low': '189.4700',
   '4. close': '189.5700',
   '5. volume': '1367147'},
  '2024-01-19 11:15:00': {'1. open': '189.8300',
   '2. high': '190.0600',
   '3. low': '189.8200',
   '4. close': '189.9100',
   '5. volume': '1327094'},
  '2024-01-19 11:00:00': {'1. open': '189.7800',
   '2. high': '189.9900',
   '3. low': '189.5800',
   '4. close': '189.8350',
   '5. volume': '1704207'},
  '2024-01-19 10:45:00': {'1. open': '189.9500',
   '2. high': '190.1600',
   '3. low': '189.7300',
   '4. close': '189.7900',
   '5. volume': '2627683'},
  '2024-01-19 10:30:00': {'1. open': '189.9350',
   '2. high': '189.9500',
   '3. low': '189.6200',
   '4. close': '189.9450',
   '5. volume': '1913084'},
  '2024-01-19 10:15:00': {'1. open': '189.2850',
   '2. high': '189.9650',
   '3. low': '189.2850',
   '4. close': '189.9400',
   '5. volume': '1883094'},
  '2024-01-19 10:00:00': {'1. open': '189.5900',
   '2. high': '189.7100',
   '3. low': '188.9100',
   '4. close': '189.2940',
   '5. volume': '2257971'},
  '2024-01-19 09:45:00': {'1. open': '189.6100',
   '2. high': '189.8800',
   '3. low': '189.3710',
   '4. close': '189.5900',
   '5. volume': '2478629'},
  '2024-01-19 09:30:00': {'1. open': '189.3300',
   '2. high': '189.8250',
   '3. low': '188.8200',
   '4. close': '189.6100',
   '5. volume': '8360045'},
  '2024-01-19 09:15:00': {'1. open': '188.8900',
   '2. high': '189.5300',
   '3. low': '188.5000',
   '4. close': '189.3700',
   '5. volume': '298488'},
  '2024-01-19 09:00:00': {'1. open': '189.1600',
   '2. high': '189.1600',
   '3. low': '188.7600',
   '4. close': '188.8850',
   '5. volume': '91137'},
  '2024-01-19 08:45:00': {'1. open': '189.3500',
   '2. high': '189.5000',
   '3. low': '188.8900',
   '4. close': '189.1700',
   '5. volume': '97166'},
  '2024-01-19 08:30:00': {'1. open': '189.7000',
   '2. high': '193.2400',
   '3. low': '186.8200',
   '4. close': '189.3800',
   '5. volume': '41402'},
  '2024-01-19 08:15:00': {'1. open': '189.9300',
   '2. high': '190.1600',
   '3. low': '188.6300',
   '4. close': '189.6900',
   '5. volume': '212386'},
  '2024-01-19 08:00:00': {'1. open': '190.1000',
   '2. high': '190.5000',
   '3. low': '188.6300',
   '4. close': '189.9300',
   '5. volume': '217803'},
  '2024-01-19 07:45:00': {'1. open': '189.5700',
   '2. high': '189.8700',
   '3. low': '189.5700',
   '4. close': '189.8500',
   '5. volume': '19238'},
  '2024-01-19 07:30:00': {'1. open': '189.8300',
   '2. high': '189.9000',
   '3. low': '189.5500',
   '4. close': '189.6000',
   '5. volume': '31691'},
  '2024-01-19 07:15:00': {'1. open': '189.8800',
   '2. high': '189.9500',
   '3. low': '189.6700',
   '4. close': '189.8000',
   '5. volume': '40940'},
  '2024-01-19 07:00:00': {'1. open': '190.2000',
   '2. high': '190.2200',
   '3. low': '189.8100',
   '4. close': '189.9300',
   '5. volume': '58928'},
  '2024-01-19 06:45:00': {'1. open': '190.3900',
   '2. high': '190.4000',
   '3. low': '190.1500',
   '4. close': '190.2300',
   '5. volume': '12300'},
  '2024-01-19 06:30:00': {'1. open': '189.9200',
   '2. high': '190.5800',
   '3. low': '189.9000',
   '4. close': '190.3900',
   '5. volume': '99675'},
  '2024-01-19 06:15:00': {'1. open': '189.9000',
   '2. high': '189.9500',
   '3. low': '189.8000',
   '4. close': '189.9300',
   '5. volume': '10865'},
  '2024-01-19 06:00:00': {'1. open': '189.6500',
   '2. high': '189.9900',
   '3. low': '189.5100',
   '4. close': '189.9000',
   '5. volume': '37300'},
  '2024-01-19 05:45:00': {'1. open': '189.5400',
   '2. high': '189.7900',
   '3. low': '189.5100',
   '4. close': '189.6500',
   '5. volume': '21411'},
  '2024-01-19 05:30:00': {'1. open': '189.3300',
   '2. high': '189.5600',
   '3. low': '189.3000',
   '4. close': '189.5400',
   '5. volume': '11862'},
  '2024-01-19 05:15:00': {'1. open': '189.3000',
   '2. high': '189.3600',
   '3. low': '189.2100',
   '4. close': '189.3400',
   '5. volume': '7382'},
  '2024-01-19 05:00:00': {'1. open': '189.4700',
   '2. high': '189.4700',
   '3. low': '189.2400',
   '4. close': '189.3000',
   '5. volume': '10733'},
  '2024-01-19 04:45:00': {'1. open': '189.0800',
   '2. high': '189.4700',
   '3. low': '189.0500',
   '4. close': '189.4500',
   '5. volume': '13156'},
  '2024-01-19 04:30:00': {'1. open': '189.7100',
   '2. high': '189.7500',
   '3. low': '189.0000',
   '4. close': '189.0500',
   '5. volume': '18600'},
  '2024-01-19 04:15:00': {'1. open': '189.5000',
   '2. high': '189.9500',
   '3. low': '189.5000',
   '4. close': '189.7000',
   '5. volume': '20535'},
  '2024-01-19 04:00:00': {'1. open': '189.2500',
   '2. high': '189.8200',
   '3. low': '188.8900',
   '4. close': '189.5100',
   '5. volume': '30855'},
  '2024-01-18 19:45:00': {'1. open': '188.5750',
   '2. high': '188.6900',
   '3. low': '188.3600',
   '4. close': '188.6900',
   '5. volume': '14331'},
  '2024-01-18 19:30:00': {'1. open': '188.6900',
   '2. high': '188.6900',
   '3. low': '188.5500',
   '4. close': '188.5750',
   '5. volume': '7374'},
  '2024-01-18 19:15:00': {'1. open': '188.5400',
   '2. high': '188.6900',
   '3. low': '188.5400',
   '4. close': '188.6500',
   '5. volume': '9828'},
  '2024-01-18 19:00:00': {'1. open': '188.6000',
   '2. high': '188.6500',
   '3. low': '188.5100',
   '4. close': '188.5700',
   '5. volume': '9488'},
  '2024-01-18 18:45:00': {'1. open': '188.3900',
   '2. high': '188.6300',
   '3. low': '188.3600',
   '4. close': '188.6000',
   '5. volume': '10782'},
  '2024-01-18 18:30:00': {'1. open': '188.4000',
   '2. high': '188.4500',
   '3. low': '188.3000',
   '4. close': '188.4500',
   '5. volume': '8269'},
  '2024-01-18 18:15:00': {'1. open': '188.3000',
   '2. high': '188.4000',
   '3. low': '188.0300',
   '4. close': '188.4000',
   '5. volume': '24431'},
  '2024-01-18 18:00:00': {'1. open': '188.2350',
   '2. high': '188.3800',
   '3. low': '188.2000',
   '4. close': '188.3000',
   '5. volume': '24127'},
  '2024-01-18 17:45:00': {'1. open': '188.0400',
   '2. high': '188.2400',
   '3. low': '187.9300',
   '4. close': '188.2250',
   '5. volume': '15625'},
  '2024-01-18 17:30:00': {'1. open': '187.7500',
   '2. high': '188.6300',
   '3. low': '187.7100',
   '4. close': '188.0400',
   '5. volume': '78379'},
  '2024-01-18 17:15:00': {'1. open': '188.2000',
   '2. high': '188.2300',
   '3. low': '187.7500',
   '4. close': '187.7980',
   '5. volume': '45093'},
  '2024-01-18 17:00:00': {'1. open': '188.4800',
   '2. high': '198.0240',
   '3. low': '188.0200',
   '4. close': '188.1200',
   '5. volume': '67703'},
  '2024-01-18 16:45:00': {'1. open': '188.5800',
   '2. high': '188.6400',
   '3. low': '188.4340',
   '4. close': '188.4850',
   '5. volume': '198195'},
  '2024-01-18 16:30:00': {'1. open': '188.9200',
   '2. high': '188.9200',
   '3. low': '188.5500',
   '4. close': '188.5500',
   '5. volume': '90874'},
  '2024-01-18 16:15:00': {'1. open': '188.8100',
   '2. high': '196.2550',
   '3. low': '188.5300',
   '4. close': '188.9100',
   '5. volume': '569030'},
  '2024-01-18 16:00:00': {'1. open': '188.6300',
   '2. high': '188.8500',
   '3. low': '188.2380',
   '4. close': '188.8200',
   '5. volume': '17921100'},
  '2024-01-18 15:45:00': {'1. open': '188.7200',
   '2. high': '188.9000',
   '3. low': '188.5100',
   '4. close': '188.7300',
   '5. volume': '4877046'},
  '2024-01-18 15:30:00': {'1. open': '188.9600',
   '2. high': '188.9900',
   '3. low': '188.6550',
   '4. close': '188.7200',
   '5. volume': '2105753'},
  '2024-01-18 15:15:00': {'1. open': '188.9900',
   '2. high': '189.0850',
   '3. low': '188.7450',
   '4. close': '188.9600',
   '5. volume': '1692053'},
  '2024-01-18 15:00:00': {'1. open': '188.9800',
   '2. high': '189.1300',
   '3. low': '188.8750',
   '4. close': '188.9850',
   '5. volume': '1475247'},
  '2024-01-18 14:45:00': {'1. open': '188.8000',
   '2. high': '189.1400',
   '3. low': '188.7050',
   '4. close': '188.9750',
   '5. volume': '1583479'},
  '2024-01-18 14:30:00': {'1. open': '188.9250',
   '2. high': '189.1200',
   '3. low': '188.7450',
   '4. close': '188.8000',
   '5. volume': '2315380'},
  '2024-01-18 14:15:00': {'1. open': '188.6450',
   '2. high': '188.9500',
   '3. low': '188.5600',
   '4. close': '188.9240',
   '5. volume': '1715567'},
  '2024-01-18 14:00:00': {'1. open': '188.1700',
   '2. high': '188.6500',
   '3. low': '188.1600',
   '4. close': '188.6500',
   '5. volume': '1503463'},
  '2024-01-18 13:45:00': {'1. open': '187.9750',
   '2. high': '188.2600',
   '3. low': '187.8600',
   '4. close': '188.1600',
   '5. volume': '1370664'},
  '2024-01-18 13:30:00': {'1. open': '186.9300',
   '2. high': '188.0910',
   '3. low': '186.9200',
   '4. close': '187.9750',
   '5. volume': '1926439'},
  '2024-01-18 13:15:00': {'1. open': '187.5300',
   '2. high': '187.5600',
   '3. low': '186.7500',
   '4. close': '186.9250',
   '5. volume': '2049391'},
  '2024-01-18 13:00:00': {'1. open': '187.8500',
   '2. high': '187.8600',
   '3. low': '187.4200',
   '4. close': '187.5450',
   '5. volume': '1348183'},
  '2024-01-18 12:45:00': {'1. open': '187.7300',
   '2. high': '187.8800',
   '3. low': '187.6750',
   '4. close': '187.8500',
   '5. volume': '1288615'},
  '2024-01-18 12:30:00': {'1. open': '187.9300',
   '2. high': '187.9300',
   '3. low': '187.5000',
   '4. close': '187.7400',
   '5. volume': '1286945'},
  '2024-01-18 12:15:00': {'1. open': '187.9700',
   '2. high': '188.0500',
   '3. low': '187.6800',
   '4. close': '187.9300',
   '5. volume': '1439530'},
  '2024-01-18 12:00:00': {'1. open': '188.4850',
   '2. high': '188.5300',
   '3. low': '187.8050',
   '4. close': '187.9700',
   '5. volume': '2524343'},
  '2024-01-18 11:45:00': {'1. open': '188.3900',
   '2. high': '188.6700',
   '3. low': '188.2600',
   '4. close': '188.4720',
   '5. volume': '1711585'},
  '2024-01-18 11:30:00': {'1. open': '188.7650',
   '2. high': '188.7800',
   '3. low': '188.3400',
   '4. close': '188.3900',
   '5. volume': '2693440'},
  '2024-01-18 11:15:00': {'1. open': '188.2900',
   '2. high': '188.9600',
   '3. low': '188.2900',
   '4. close': '188.7700',
   '5. volume': '2713930'},
  '2024-01-18 11:00:00': {'1. open': '188.0900',
   '2. high': '188.2900',
   '3. low': '187.5600',
   '4. close': '188.2800',
   '5. volume': '3081646'}},
 {'1. Information': 'Intraday (15min) open, high, low, close prices and volume',
  '2. Symbol': 'AAPL',
  '3. Last Refreshed': '2024-01-19 19:45:00',
  '4. Interval': '15min',
  '5. Output Size': 'Compact',
  '6. Time Zone': 'US/Eastern'})

In [28]:
#Bring data in DataFarme Format

ts2 = TimeSeries(key=API_KEY, output_format="pandas")

In [29]:
ts2.get_intraday("AAPL")

(                     1. open  2. high   3. low  4. close  5. volume
 date
 2024-01-19 19:45:00  191.230   191.31  191.160   191.230     7448.0
 2024-01-19 19:30:00  191.220   191.25  191.060   191.220     6076.0
 2024-01-19 19:15:00  191.110   191.38  191.110   191.220     3551.0
 2024-01-19 19:00:00  191.300   191.30  191.090   191.240    11999.0
 2024-01-19 18:45:00  191.430   191.43  191.270   191.300     8553.0
 ...                      ...      ...      ...       ...        ...
 2024-01-18 12:00:00  188.485   188.53  187.805   187.970  2524343.0
 2024-01-18 11:45:00  188.390   188.67  188.260   188.472  1711585.0
 2024-01-18 11:30:00  188.765   188.78  188.340   188.390  2693440.0
 2024-01-18 11:15:00  188.290   188.96  188.290   188.770  2713930.0
 2024-01-18 11:00:00  188.090   188.29  187.560   188.280  3081646.0

 [100 rows x 5 columns],
 {'1. Information': 'Intraday (15min) open, high, low, close prices and volume',
  '2. Symbol': 'AAPL',
  '3. Last Refreshed': '2024-01-19 19:45:00',
  '4. Interval': '15min',
  '5. Output Size': 'Compact',
  '6. Time Zone': 'US/Eastern'})

In [33]:
df_apple2, meta_data =  ts2.get_intraday("AAPL", outputsize="full")

In [31]:
meta_data

{'1. Information': 'Intraday (15min) open, high, low, close prices and volume',
 '2. Symbol': 'AAPL',
 '3. Last Refreshed': '2024-01-19 19:45:00',
 '4. Interval': '15min',
 '5. Output Size': 'Full size',
 '6. Time Zone': 'US/Eastern'}

In [36]:
df_apple2.head(20)

                     1. open  2. high   3. low  4. close   5. volume
date
2024-01-19 19:45:00  191.230  191.310  191.160   191.230      7448.0
2024-01-19 19:30:00  191.220  191.250  191.060   191.220      6076.0
2024-01-19 19:15:00  191.110  191.380  191.110   191.220      3551.0
2024-01-19 19:00:00  191.300  191.300  191.090   191.240     11999.0
2024-01-19 18:45:00  191.430  191.430  191.270   191.300      8553.0
2024-01-19 18:30:00  191.450  191.520  191.405   191.420      4244.0
2024-01-19 18:15:00  191.490  191.560  191.380   191.500    119949.0
2024-01-19 18:00:00  191.435  191.550  191.390   191.510      2385.0
2024-01-19 17:45:00  191.440  191.490  191.380   191.435      3421.0
2024-01-19 17:30:00  191.460  191.500  181.657   191.420      5945.0
2024-01-19 17:15:00  191.520  200.063  191.450   191.475      3937.0
2024-01-19 17:00:00  191.555  191.590  191.500   191.530      5670.0
2024-01-19 16:45:00  191.460  191.760  191.460   191.555     23477.0
2024-01-19 16:30:00  191.390  191.560  191.350   191.465    225141.0
2024-01-19 16:15:00  191.490  198.870  190.754   191.380     52358.0
2024-01-19 16:00:00  191.560  191.600  190.893   191.490  21590783.0
2024-01-19 15:45:00  191.410  191.820  191.320   191.580   3995109.0
2024-01-19 15:30:00  191.434  191.650  191.390   191.411   1721562.0
2024-01-19 15:15:00  191.570  191.640  191.320   191.435   1395544.0
2024-01-19 15:00:00  191.654  191.740  191.480   191.570   1621255.0